export const strings = {
  common: {
    errorHeading: "Something went wrong",
    errorRetry: "Try again",
    validation: {
      required: "Required",
      invalidAmount: "Enter a valid amount",
      endDateAfterStart: "Must be after start date",
    },
    filter: {
      filterButton: "Filter",
      filtersTitle: "Filters",
      addFilter: "Add filter",
      clearAllFilters: "Clear all filters",
      applyFilter: "Apply filter",
    },
  },

  app: {
    name: "RentPortal",
    tagline: "A rent management portal.",
  },

  nav: {
    manager: "Manager",
    tenant: "Tenant",
  },

  statusPill: {
    allPaid: "All Paid",
    paid: "Paid",
    outstanding: "Outstanding",
    overdue: "Overdue",
    vacant: "Vacant",
    upcoming: "Upcoming",
  },

  paymentTable: {
    heading: "Payment history",
    colPeriod: "Period",
    colDue: "Amount Due",
    colPaid: "Amount Paid",
    colDate: "Paid Date",
    colMethod: "Method",
    colStatus: "Status",
    notPaid: "-",
    emptyTitle: "No payments recorded",
    emptyDescription: "Payments will appear here once a lease is active.",
    statusPill: {
      paid: "Paid",
      outstanding: "Outstanding",
      overdue: "Overdue",
    },
    actions: {
      sendReminder: "Send Reminder",
      lastReminderSent: "Last sent:",
      markPaid: "Mark as Paid",
      markingPaid: "Processing…",
      reminderToast: (tenantName: string) => `Reminder sent to ${tenantName} for overdue rent.`,
    },
  },

  manager: {
    dashboard: {
      title: "Manager Dashboard",
      subtitle: "Overview of your portfolio performance.",
      pageTitle: "Dashboard",
      pageSubtitlePrefix: "Your portfolio at a glance -",

      loading: "Loading dashboard…",
      error: "Could not load dashboard data.",
      errorRetry: "Try again",
      emptyTitle: "No data yet",
      emptyDescription: "Add properties to see your dashboard.",

      stats: {
        properties: "Properties",
        propertiesSubtitle: (total: number) => `${total} total units`,
        propertiesLabel: (units: number) => `Properties · ${units} units`,
        occupancy: "Occupancy",
        occupancySubtitle: (vacant: number) => `${vacant} vacant`,
        occupancyLabel: (vacant: number) => `Occupied · ${vacant} vacant`,
        monthlyRent: "Monthly Rent",
        monthlyRentLabel: "Monthly rent",
        monthlyRentSubtitle: "across active leases",
        collectionRate: "Collection Rate",
        collectionRateLabel: "Collection rate",
        collectionRateSubtitle: (amount: string) => `${amount} collected`,
      },

      propertiesSummary: (count: number) => `${count} properties`,
      propertiesOverdueCount: (count: number) => `· ${count} overdue`,
      viewAllProperties: "View all properties",

      revenueChart: {
        title: "Monthly Revenue",
        subtitle: (months: number) => `Expected vs collected over last ${months} months`,
        barExpected: "Expected",
        barCollected: "Collected",
        empty: "No revenue data",
        periodOptions: {
          months3: "Last 3 months",
          months6: "Last 6 months",
          months12: "Last 12 months",
        },
      },

      paymentChart: {
        title: "Payment Status",
        subtitle: "Breakdown across all leases",
        paid: "Paid",
        outstanding: "Outstanding",
        overdue: "Overdue",
        empty: "No payment data",
        collected: "collected",
      },

      propertiesTable: {
        heading: (count: number) => `Properties (${count})`,
        colId: "ID",
        colName: "Property Name",
        colAddress: "Address",
        colUnits: "Units",
        colRent: "Monthly Rent",
        colStatus: "Status",
        occupiedSuffix: "occupied",
        viewLink: "View",
        empty: "No properties",
        emptyDescription: "Add your first property to get started.",
      },

      attentionHero: {
        label: "Needs attention",
        outstandingPrefix: "outstanding across",
        outstandingCycleSuffix: "leases this cycle.",
        overdueWarning: (count: number) =>
          `${count} are now overdue - clear these first to protect collection rate.`,
        overdueLabel: (count: number) => `Overdue · ${count} lease${count !== 1 ? "s" : ""}`,
        outstandingLabel: (count: number) =>
          `Outstanding · ${count} lease${count !== 1 ? "s" : ""}`,
        reviewOverdue: "Review overdue",
        sendAllReminders: "Send all reminders",
        sendAllRemindersSuccess: (n: number) =>
          `Reminders sent to ${n} tenant${n !== 1 ? "s" : ""}.`,
        sendAllRemindersError: "Failed to send some reminders. Please try again.",
        atRiskTitle: "At-risk leases",
        viewAll: "View all",
        daysOverdue: (days: number) => `${days} days overdue`,
        outstanding: "Outstanding",
      },
    },

    propertyDetail: {
      backLink: "Back to Dashboard",
      loading: "Loading property…",
      error: "Could not load property details.",
      errorRetry: "Try again",
      emptyTitle: "Property not found",
      emptyDescription: "This property does not exist or has been removed.",

      stats: {
        totalUnits: "Total Units",
        occupied: "Occupied",
        occupiedLabel: (vacantCount: number) => `Occupied · ${vacantCount} vacant`,
        vacant: "Vacant",
        monthlyRent: "Monthly Rent",
        occupancySub: (leased: number, total: number) => `${leased} of ${total} leased`,
        vacantSub: (count: number) => `${count} available`,
        rentSub: "across active leases",
      },

      overdueAlert: (count: number) =>
        `${count} unit${count !== 1 ? "s" : ""} overdue - action needed`,

      unitMixBar: {
        heading: "Unit status breakdown",
        overdue: "Overdue",
        outstanding: "Outstanding",
        paid: "Paid",
        vacant: "Vacant",
      },

      unitsTable: {
        heading: (count: number) => `Units (${count})`,
        colUnit: "Unit",
        colTenant: "Tenant",
        colRent: "Monthly Rent",
        colLease: "Lease Period",
        colStatus: "Status",
        colAction: "",
        vacant: "Vacant",
        leasePeriod: (start: string, end: string) => `${start} – ${end}`,
        viewLink: "View",
        open: "Open",
        sendReminder: "Send reminder",
        addLease: "Add lease",
        empty: "No units found",
        emptyDescription: "This property has no units yet.",
      },
    },

    addLease: {
      title: (unitLabel: string) => `Add Lease - ${unitLabel}`,
      subtitle: "Assign a tenant and set lease terms for this unit.",
      fieldTenant: "Tenant",
      fieldTenantPlaceholder: "Select a tenant",
      fieldTenantHasLease: "(has lease)",
      createNewTenant: "Create new tenant",
      selectExistingTenant: "Select existing tenant",
      fieldRent: "Monthly Rent ($)",
      fieldRentPlaceholder: "e.g. 2500",
      fieldStartDate: "Start Date",
      fieldEndDate: "End Date",
      fieldTerms: "Terms (optional)",
      fieldTermsPlaceholder: "e.g. No pets, no subletting.",
      submit: "Create Lease",
      submitting: "Creating…",
      cancel: "Cancel",
      successToast: (unitLabel: string) => `Lease created for ${unitLabel}.`,
      newTenant: {
        heading: "New Tenant",
        fieldName: "Full Name",
        fieldNamePlaceholder: "e.g. Alice Johnson",
        fieldEmail: "Email",
        fieldEmailPlaceholder: "e.g. alice@example.com",
        fieldContact: "Contact (optional)",
        fieldContactPlaceholder: "e.g. +1 512-555-0101",
      },
    },

    addProperty: {
      title: "Add Property",
      subtitle: "Fill in the details to add a new property to your portfolio.",
      fieldName: "Property Name",
      fieldNamePlaceholder: "e.g. Maple Heights",
      fieldAddress: "Address",
      fieldAddressPlaceholder: "e.g. 123 Main St, Austin TX 78701",
      fieldManagerName: "Manager Name",
      fieldManagerNamePlaceholder: "e.g. James Carter",
      fieldManagerEmail: "Manager Email",
      fieldManagerEmailPlaceholder: "e.g. james@rentportal.com",
      fieldManagerContact: "Manager Contact",
      fieldManagerContactPlaceholder: "e.g. +1 512-555-0100",
      fieldUnitCount: "Number of Units",
      fieldUnitCountHint: "Blank units will be created. You can add tenants and leases later.",
      submit: "Add Property",
      submitting: "Adding…",
      cancel: "Cancel",
      successToast: (name: string) => `"${name}" added successfully.`,
    },

    propertiesList: {
      title: "Properties",
      subtitle: (count: number) => `${count} properties`,
      overdueCount: (count: number) => `${count} overdue`,
      vacantCount: (count: number) => `${count} vacant`,
      addPropertyButton: "Add Property",
      error: "Failed to load properties.",
      emptyTitle: "No properties yet",
      emptyDescription: "Add your first property to get started.",
      noUnitsFound: "No units found",
      vacant: "Vacant",
      occupied: "occupied",
      cols: {
        property: "Property",
        units: "Units",
        rentPerMonth: "Rent/mo",
        status: "Status",
      },
      tabs: {
        all: "All",
        overdue: "Overdue",
        outstanding: "Outstanding",
        paid: "Paid",
        vacant: "Vacant",
      },
      groups: {
        overdue: "Overdue",
        outstanding: "Outstanding",
        paid: "Paid",
        vacant: "Vacant",
        upcoming: "Upcoming",
      },
      unitMenu: {
        addLease: "Add lease",
        sendReminder: "Send reminder",
        markPaid: "Mark as paid",
        lastSent: (time: string) => `Last sent ${time}`,
        reminderSuccess: (name: string) => `Reminder sent to ${name}.`,
        paymentSuccess: "Payment marked as paid.",
        failedReminder: "Failed to send reminder.",
        failedMarkPaid: "Failed to mark as paid.",
        failedAddLease: "Failed to create lease.",
        failedAddProperty: "Failed to add property.",
      },
      addPropertyModal: {
        unitsLabel: "Units",
        addUnit: "Add unit",
        noUnitsHint: 'No units added yet. Click "Add unit" to add one.',
        unitPlaceholder: (i: number) => `e.g. Unit ${i} or 2A`,
      },
    },

    paymentsList: {
      title: "Payments",
      loading: "Loading payments…",
      error: "Could not load payments.",
      emptyTitle: "No payments yet",
      emptyDescription: "Payments will appear here once leases are active.",
      tabs: { all: "All", overdue: "Overdue", outstanding: "Outstanding", paid: "Paid" },
      filtersTitle: "Filters",
      needImmediateAction: "need immediate action",
      subtitle: (count: number) => `${count} records across all leases`,
      filterButton: "Filter",
      addFilter: "Add filter",
      clearAllFilters: "Clear all filters",
      applyFilter: "Apply filter",
      noMatch: "No payments match",
      noMatchDescription: "Try adjusting or clearing your filters.",
      results: (shown: number, total: number) => `${shown} of ${total} results`,
      searchLabel: "Search",
      searchPlaceholder: "Tenant, property or unit…",
      columnsLabel: "Columns",
      cols: {
        tenant: "Tenant",
        propertyUnit: "Property / Unit",
        period: "Period",
        amount: "Amount",
        paidOn: "Paid on",
        status: "Status",
      },
      summary: {
        collected: "Collected",
        outstanding: "Outstanding",
        overdue: "Overdue",
        payments: (count: number) => `${count} payments`,
      },
      filterCols: {
        status: "Status",
        property: "Property",
        period: "Period",
        amount: "Amount",
      },
      amountOptions: [
        { value: "lt1k", label: "Under $1,000" },
        { value: "1k2k", label: "$1,000 – $2,000" },
        { value: "2k3k", label: "$2,000 – $3,000" },
        { value: "gt3k", label: "Over $3,000" },
      ] as const,
      rowMenu: {
        sendReminder: "Send reminder",
        markPaid: "Mark as paid",
        lastSent: (time: string) => `Last sent ${time}`,
        reminderSuccess: (name: string) => `Reminder sent to ${name}.`,
        paymentSuccess: "Payment marked as paid.",
        failedReminder: "Failed to send reminder.",
        failedMarkPaid: "Failed to mark as paid.",
      },
    },

    tenantsList: {
      title: "Tenants",
      loading: "Loading tenants…",
      error: "Could not load tenants.",
      emptyTitle: "No tenants yet",
      emptyDescription: "Tenants will appear here once leases are created.",
      noActiveLease: "No active lease",
      noMatch: "No tenants match",
      noMatchDescription: "Try adjusting your search or filters.",
      results: (n: number, total: number) => `${n} of ${total} tenants`,
      searchPlaceholder: "Tenant name, email or property…",
      filterButton: "Filter",
      filtersTitle: "Filters",
      addFilter: "Add filter",
      clearAllFilters: "Clear all filters",
      applyFilter: "Apply filter",
      filterCols: {
        payment: "Payment",
        kyc: "KYC",
      },
      addTenantButton: "Add Tenant",
      addTenant: {
        title: "Add Tenant",
        subtitle: "Create a new tenant profile. You can assign a lease later.",
        fieldName: "Full Name",
        fieldNamePlaceholder: "e.g. Alice Johnson",
        fieldEmail: "Email",
        fieldEmailPlaceholder: "e.g. alice@example.com",
        fieldContact: "Contact (optional)",
        fieldContactPlaceholder: "e.g. +1 512-555-0101",
        submit: "Add Tenant",
        submitting: "Adding…",
        cancel: "Cancel",
        successToast: (name: string) => `"${name}" added successfully.`,
        failedToast: "Failed to add tenant.",
      },
    },

    tenantProfile: {
      backLink: "Back",
      loading: "Loading tenant profile…",
      error: "Could not load tenant profile.",
      emptyTitle: "Tenant not found",
      emptyDescription: "This tenant does not exist or has been removed.",

      info: {
        heading: "Tenant Info",
        name: "Name",
        email: "Email",
        contact: "Contact",
        kycStatus: "KYC Status",
        kycVerifiedOn: "Verified On",
        kycDocument: "KYC Document",
        kycDocumentLink: "View Document",
        kycDocumentNone: "Not uploaded",
        kycStatusLabels: {
          verified: "Verified",
          pending: "Pending",
          not_submitted: "Not Submitted",
        },
      },

      standing: {
        heading: "Payment Reliability Score",
        score: "Score",
        totalPayments: "Total Payments",
        onTime: "on time payments",
        noData: "No payment history yet",
        labelColors: {
          Excellent: { bg: "bg-success-50", text: "text-success-700" },
          Good: { bg: "bg-brand-50", text: "text-brand-600" },
          Fair: { bg: "bg-warning-50", text: "text-warning-700" },
          Poor: { bg: "bg-danger-50", text: "text-danger-700" },
        },
      },

      lease: {
        heading: "Current Lease",
        property: "Property",
        unit: "Unit",
        monthlyRent: "Monthly Rent",
        leaseDate: "Lease Date",
        startDate: "Start Date",
        endDate: "End Date",
        terms: "Terms",
        leaseDocument: "Lease Document",
        leaseDocumentLink: "View Document",
        leaseDocumentNone: "Not uploaded",
        noLease: "No active lease",
      },

      payments: {
        heading: (count: number) => `Payment History (${count})`,
        historyTitle: "Payment history",
        loadingHistory: "Loading payments…",
        empty: "No payments recorded",
        colPeriod: "Period",
        colDue: "Amount Due",
        colPaid: "Amount Paid",
        colDate: "Paid Date",
        colMethod: "Method",
        colStatus: "Status",
        notPaid: "-",
      },

      statusPill: {
        paid: "Paid",
        outstanding: "Outstanding",
        overdue: "Overdue",
      },
    },

    unitDetail: {
      backLink: "Back to Property",
      loading: "Loading unit…",
      error: "Could not load unit details.",
      emptyTitle: "Unit not found",
      emptyDescription: "This unit does not exist or has been removed.",

      tenant: {
        heading: "Tenant",
        name: "Name",
        email: "Email",
        contact: "Contact",
        noTenant: "No tenant assigned",
        viewProfile: "View Tenant Profile",
      },

      lease: {
        heading: "Lease Details",
        monthlyRent: "Monthly Rent",
        leasePeriod: "Lease Period",
        terms: "Terms",
        leaseDocument: "Lease Document",
        leaseDocumentLink: "View Lease Document",
        leaseDocumentNone: "Not uploaded",
        noLease: "No active lease",
      },

      payments: {
        heading: (count: number) => `Payment History (${count})`,
        loadingHistory: "Loading payments…",
        empty: "No payments recorded",
        noLeaseTitle: "No lease on this unit",
        noLeaseDescription: "Add a lease to start tracking payments.",
        colPeriod: "Period",
        colDue: "Amount Due",
        colPaid: "Amount Paid",
        colDate: "Paid Date",
        colMethod: "Method",
        colStatus: "Status",
        colActions: "",
        notPaid: "-",
        sendReminder: "Send Reminder",
        markPaid: "Mark as Paid",
        reminderSent: "Reminder sent",
        markingPaid: "Processing…",
      },

      statusPill: {
        paid: "Paid",
        outstanding: "Outstanding",
        overdue: "Overdue",
        vacant: "Vacant",
      },
    },
  },
  tenant: {
    propertyInfo: {
      heading: "Property Details",
      name: "Property",
      address: "Address",
      unit: "Unit",
      noProperty: "No property assigned.",
    },
    managerInfo: {
      heading: "Property Manager",
      name: "Name",
      email: "Email",
      contact: "Contact",
      noManager: "No manager assigned.",
    },
    leaseDetails: {
      heading: "Lease Details",
      monthlyRent: "Monthly Rent",
      leasePeriod: "Lease Period",
      terms: "Terms",
      leaseDocument: "Lease Document",
      leaseDocumentLink: "View Document",
      leaseDocumentNone: "Not uploaded",
      noLease: "No active lease.",
    },
    dashboard: {
      heading: (name: string) => `Welcome back, ${name}`,
      subheading: "Your rental dashboard",
      loading: "Loading your dashboard…",
      error: "Failed to load dashboard.",
      emptyTitle: "Profile not found",
      emptyDescription: "Your tenant profile could not be loaded.",
      hero: {
        overdue: "Payment overdue",
        outstanding: "Payment outstanding",
        payNow: "Pay rent now",
        dueFor: (period: string) => `Due for ${period}`,
        pastDue: " - this payment is past due.",
        allClearTitle: "All payments up to date",
        allClearDescription: "You have no outstanding or overdue payments.",
      },
      paymentHistoryTitle: "Payment history",
      payments: {
        heading: (count: number) => `Payment History [${count}] `,
        empty: "No payment records yet.",
        emptyDescription: "Payments will appear here once your first due date arrives.",
        payButton: "Pay Rent",
      },
    },
    payRentModal: {
      title: (period: string) => `Pay Rent - ${period}`,
      amount: "Amount Due",
      selectMethod: "Payment Method",
      noMethods: "No payment methods saved.",
      methodsLoading: "Loading…",
      addMethodPlaceholder: "e.g. Chase ••••4242",
      addMethodLabel: "Add a payment method",
      addMethodButton: "Add",
      addMethodLoading: "Adding…",
      payButton: "Pay Now",
      payLoading: "Processing…",
      cancel: "Cancel",
      successToast: "Rent paid successfully.",
      errorPrefix: "Payment failed:",
    },
  },
} as const;
